data_engineering_skills = {
    'Airflow': ['Airflow', 'Apache Airflow'],
    'Ansible': ['Ansible'],
    'Athena': ['Athena', 'Amazon Athena'],
    'Avro': ['Avro', 'Apache Avro'],
    'AWS': ['AWS', 'Amazon Web Services'],
    'AWS Glue': ['AWS Glue'],
    'Azure': ['Azure', 'Microsoft Azure'],
    'Azure Data Factory': ['Azure Data Factory', 'ADF'],
    'Azure Synapse Analytics': ['Azure Synapse Analytics', 'ASA', 'Microsoft Azure Synapse Analytics'],
    'Batch Processing': ['Batch Processing'],
    'Beam': ['Beam', 'Apache Beam'],
    'BigQuery': ['BigQuery', 'Google BigQuery'],
    'Cassandra': ['Cassandra'],
    'Chef': ['Chef'],
    'CI/CD': ['CI/CD', 'Continuous Integration', 'Continuous Deployment'],
    'Couchbase': ['Couchbase'],
    'Data Catalog': ['Data Catalog'],
    'Data Fabric': ['Data Fabric'],
    'Dataform': ['Dataform'],
    'Data Governance': ['Data Governance'],
    'Data Lakes': ['Data Lakes', 'Data Lake'],
    'Data Mesh': ['Data Mesh'],
    'Data Modeling': ['Data Modeling', 'ERD', 'Entity-Relationship Diagram'],
    'Data Pipelines': ['Data Pipelines', 'Data Pipeline'],
    'Data Quality': ['Data Quality'],
    'Data Vault': ['Data Vault'],
    'Data Virtualization': ['Data Virtualization'],
    'Data Warehousing': ['Data Warehousing', 'Data Warehouse', 'DWH'],
    'Databricks': ['Databricks'],
    'DataOps': ['DataOps'],
    'dbt': ['dbt', 'data build tool'],
    'Delta Lake': ['Delta Lake'],
    'Docker': ['Docker'],
    'Druid': ['Druid', 'Apache Druid'],
    'DynamoDB': ['DynamoDB', 'Amazon DynamoDB'],
    'Elasticsearch': ['Elasticsearch', 'ELK Stack'],
    'ELT': ['ELT', 'Extract Load Transform'],
    'ETL': ['ETL', 'Extract Transform Load'],
    'Fabric': ['Fabric', 'Microsoft Fabric'],
    'Flink': ['Flink', 'Apache Flink'],
    'Flume': ['Flume', 'Apache Flume'],
    'GCP': ['GCP', 'Google Cloud', 'Google Cloud Platform'],
    'Git': ['Git', 'GitHub', 'GitLab'],
    'Grafana': ['Grafana'],
    'Greenplum': ['Greenplum'],
    'Hadoop': ['Hadoop', 'HDFS'],
    'Hive': ['Hive', 'Apache Hive'],
    'Hudi': ['Hudi', 'Apache Hudi'],
    'Iceberg': ['Iceberg', 'Apache Iceberg'],
    'Impala': ['Impala', 'Apache Impala'],
    'Informatica': ['Informatica'],
    'Inmon Methodology': ['Inmon', 'Inmon Methodology', 'Corporate Information Factory'],
    'Java': ['Java'],
    'Jenkins': ['Jenkins'],
    'Jupyter': ['Jupyter', 'Jupyter Notebooks'],
    'Kafka': ['Kafka', 'Apache Kafka'],
    'Kappa Architecture': ['Kappa Architecture'],
    'Kibana': ['Kibana'],
    'Kimball Methodology': ['Kimball', 'Kimball Methodology', 'Dimensional Modeling'],
    'Kubernetes': ['Kubernetes', 'K8s'],
    'Lambda Architecture': ['Lambda Architecture'],
    'Linux': ['Linux'],
    'Logstash': ['Logstash'],
    'Looker': ['Looker'],
    'Looker Studio': ['Looker Studio'],
    'Matillion': ['Matillion', 'Matillion ETL'],
    'MLOps': ['MLOps', 'Machine Learning Operations'],
    'MongoDB': ['MongoDB'],
    'Neo4j': ['Neo4j'],
    'Nifi': ['Nifi', 'Apache Nifi'],
    'NoSQL': ['NoSQL', 'MongoDB', 'Cassandra', 'DynamoDB', 'DocumentDB'],
    'NumPy': ['NumPy'],
    'Oozie': ['Oozie', 'Apache Oozie'],
    'Oracle': ['Oracle', 'Oracle Database'],
    'ORC': ['ORC', 'Apache ORC'],
    'Pandas': ['Pandas'],
    'Parquet': ['Parquet', 'Apache Parquet'],
    'Pig': ['Pig', 'Apache Pig'],
    'PostgreSQL': ['PostgreSQL', 'Postgres'],
    'Power BI': ['Power BI', 'PowerBI'],
    'Presto': ['Presto'],
    'Prometheus': ['Prometheus'],
    'Pulsar': ['Pulsar', 'Apache Pulsar'],
    'Puppet': ['Puppet'],
    'Python': ['Python'],
    'RabbitMQ': ['RabbitMQ'],
    'Redis': ['Redis'],
    'Redshift': ['Redshift', 'AWS Redshift', 'Amazon Redshift'],
    'SAS': ['SAS'],
    'Scala': ['Scala'],
    'Shell Scripting': ['Shell Scripting', 'Bash', 'Shell Script', 'Unix Shell'],
    'Snowflake': ['Snowflake'],
    'Spark': ['Apache Spark', 'Spark'],
    'Splunk': ['Splunk'],
    'SQL': ['SQL', 'MySQL', 'PostgreSQL', 'T-SQL', 'PL/SQL'],
    'SQL Server': ['SQL Server', 'Microsoft SQL Server'],
    'Sqoop': ['Sqoop', 'Apache Sqoop'],
    'Stream Processing': ['Stream Processing', 'Real-time Processing'],
    'Tableau': ['Tableau'],
    'Talend': ['Talend'],
    'Teradata': ['Teradata'],
    'Terraform': ['Terraform'],
    'Vertica': ['Vertica']
}